service: bh1

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  runtime: python37
  project: stageteam27
  credentials: /Users/meir.levin/Downloads/stageteam27key.json

functions:
  avg_tmp_per_city_per_day:
    handler: get_avg_tmp_per_city_per_day
    events:
      - http: path

  lowest_humid:
    handler: get_lowest_humid
    events:
      - http: path

  feels_like_rank:
    handler: get_feels_like_rank
    events:
      - http: path
