service: bee

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - package-lock.json
    - package.json

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  runtime: python37
  project: maan-284809
  credentials: 'C:\Users\meirt\Desktop\maankey.json'

functions:
  feels_like_rank:
    handler: feels_like_rank
    events:
      - http: path
